baseURL = "https://thinhblog.com/"
languageCode = "vi"
title = "Thịnh Blog"
paginate = 6
removePathAccents = true

[taxonomies]
    category = "categories"

[params]
    author = "Thịnh Nguyễn"
    shortIntro = "Hi, tôi đam mê code và lập trình"
    github = "https://github.com/npthinhdev"
    email = "npthinh1996@gmail.com"
    facebook = "https://www.facebook.com/npthinhdev"
    linkedin = "https://www.linkedin.com/in/npthinhdev"

[markup]
  [markup.highlight]
    lineNos = true
