baseURL = "https://thinhblog.com/"
languageCode = "vi"
title = "Thịnh Blog"
paginate = 6
removePathAccents = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Trang chủ"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "Giới thiệu"
    url = "/gioi-thieu/"
    weight = 2
  [[menu.main]]
    identifier = "cat"
    name = "Danh mục"
    url = ""
    weight = 3

[taxonomies]
  category = "categories"

[params]
  author = "Thịnh Nguyễn"
  shortIntro = "Hi, tôi đam mê code và lập trình"
  github = "https://github.com/npthinhdev"
  email = "npthinh1996@gmail.com"
  facebook = "https://www.facebook.com/npthinhdev"
  linkedin = "https://www.linkedin.com/in/npthinhdev"
  momo = "https://nhantien.momo.vn/fnT132uBd4J"
  paypal = "https://paypal.me/npthinh1996"

[markup]
  [markup.highlight]
    lineNos = true
